// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: crawl.proto

package crawler

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SuccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crawl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crawl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_crawl_proto_rawDescGZIP(), []int{0}
}

func (x *SuccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CrawlItemParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopID int32 `protobuf:"varint,1,opt,name=shopID,proto3" json:"shopID,omitempty"`
}

func (x *CrawlItemParam) Reset() {
	*x = CrawlItemParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crawl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrawlItemParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlItemParam) ProtoMessage() {}

func (x *CrawlItemParam) ProtoReflect() protoreflect.Message {
	mi := &file_crawl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlItemParam.ProtoReflect.Descriptor instead.
func (*CrawlItemParam) Descriptor() ([]byte, []int) {
	return file_crawl_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlItemParam) GetShopID() int32 {
	if x != nil {
		return x.ShopID
	}
	return 0
}

type Blank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Blank) Reset() {
	*x = Blank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crawl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blank) ProtoMessage() {}

func (x *Blank) ProtoReflect() protoreflect.Message {
	mi := &file_crawl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blank.ProtoReflect.Descriptor instead.
func (*Blank) Descriptor() ([]byte, []int) {
	return file_crawl_proto_rawDescGZIP(), []int{2}
}

var File_crawl_proto protoreflect.FileDescriptor

var file_crawl_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63,
	0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x49, 0x74, 0x65, 0x6d,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x44, 0x22, 0x07, 0x0a,
	0x05, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x32, 0x48, 0x0a, 0x0c, 0x43, 0x72, 0x61, 0x77, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x38, 0x0a, 0x0c, 0x43, 0x72, 0x61, 0x77, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72,
	0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x1a, 0x18, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72,
	0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_crawl_proto_rawDescOnce sync.Once
	file_crawl_proto_rawDescData = file_crawl_proto_rawDesc
)

func file_crawl_proto_rawDescGZIP() []byte {
	file_crawl_proto_rawDescOnce.Do(func() {
		file_crawl_proto_rawDescData = protoimpl.X.CompressGZIP(file_crawl_proto_rawDescData)
	})
	return file_crawl_proto_rawDescData
}

var file_crawl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_crawl_proto_goTypes = []interface{}{
	(*SuccessResponse)(nil), // 0: crawler.SuccessResponse
	(*CrawlItemParam)(nil),  // 1: crawler.CrawlItemParam
	(*Blank)(nil),           // 2: crawler.Blank
}
var file_crawl_proto_depIdxs = []int32{
	2, // 0: crawler.CrawCategory.CrawCategory:input_type -> crawler.Blank
	0, // 1: crawler.CrawCategory.CrawCategory:output_type -> crawler.SuccessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crawl_proto_init() }
func file_crawl_proto_init() {
	if File_crawl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_crawl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_crawl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrawlItemParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_crawl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_crawl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crawl_proto_goTypes,
		DependencyIndexes: file_crawl_proto_depIdxs,
		MessageInfos:      file_crawl_proto_msgTypes,
	}.Build()
	File_crawl_proto = out.File
	file_crawl_proto_rawDesc = nil
	file_crawl_proto_goTypes = nil
	file_crawl_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CrawCategoryClient is the client API for CrawCategory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CrawCategoryClient interface {
	CrawCategory(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type crawCategoryClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawCategoryClient(cc grpc.ClientConnInterface) CrawCategoryClient {
	return &crawCategoryClient{cc}
}

func (c *crawCategoryClient) CrawCategory(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/crawler.CrawCategory/CrawCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawCategoryServer is the server API for CrawCategory service.
type CrawCategoryServer interface {
	CrawCategory(context.Context, *Blank) (*SuccessResponse, error)
}

// UnimplementedCrawCategoryServer can be embedded to have forward compatible implementations.
type UnimplementedCrawCategoryServer struct {
}

func (*UnimplementedCrawCategoryServer) CrawCategory(context.Context, *Blank) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawCategory not implemented")
}

func RegisterCrawCategoryServer(s *grpc.Server, srv CrawCategoryServer) {
	s.RegisterService(&_CrawCategory_serviceDesc, srv)
}

func _CrawCategory_CrawCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawCategoryServer).CrawCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crawler.CrawCategory/CrawCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawCategoryServer).CrawCategory(ctx, req.(*Blank))
	}
	return interceptor(ctx, in, info, handler)
}

var _CrawCategory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crawler.CrawCategory",
	HandlerType: (*CrawCategoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawCategory",
			Handler:    _CrawCategory_CrawCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawl.proto",
}
